version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env # Path to your .env file
    depends_on:
      - db
    networks:
      - user-service-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data # Volume for persisting database data
    networks:
      - user-service-network

volumes:
  db-data:

networks:
  user-service-network:
