name: Production Deployment

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build for production
        run: yarn build:prod

      - name: Deploy to production server
        run: |
          # Replace the command with your deployment script or tool
          ssh user@prod-server 'bash -s' < deploy-script.sh
